### ISSUE TITLE
Subsetting across the date line

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#107]
I would expect to be able to subset a coverage across the dateline on the longitude axis with e.g. `Lon(160:-175)`, where the upper bound is a smaller value than the lower bound, but in fact crosses the date line rather than going around the globe.

example request: http://maps.ecere.com/ogcapi/collections/SRTM_ViewFinderPanorama/coverage?subset=Lat(-50:-30),Lon(160:-175)&f=png

whereas the request around the globe would be:
http://maps.ecere.com/ogcapi/collections/SRTM_ViewFinderPanorama/coverage?subset=Lat(-50:-30),Lon(-175:160)&f=png

Could we specify/require this behavior somehow in the standard?

**Comment by pebau** [comment]
My silent interpretation would be that the "(x+360) mod 360" geo CRS mechanics defines that properly.

**Comment by Schpidi** [comment]
Coverages SWG call: Proposed to specify the behavior to allow an area crossing the date line (anti meridian).

**Comment by jerstlouis** [comment]
Addressed by #122
