### ISSUE TITLE
Provide documentation in the spec about relative URIs in href values of Links

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-coverages#113]
Some implementations may use absolute URIs as href values of Links, whereas others may use relative.

https://tools.ietf.org/html/rfc8288

https://tools.ietf.org/html/rfc3986#section-5

This may be a OGC API - Common issue.

**Comment by jerstlouis** [comment]
@cmheazel Maybe Common - Part 1 needs some informative text to make this more obvious to implementers?
Should this issue be moved to Common?

**Comment by jerstlouis** [comment]
SWG 2021-08-11: Relative links are supported by RFC 8288. We will discuss in Common whether the specification could include a note for implementers.
