### ISSUE TITLE
TODOs for RFC

### ISSUE THREAD

**Issue by Schpidi** [opengeospatial/ogcapi-coverages#116]
List of TODOs to resolve before recommending to OAB for public RFC:

- [x] Agree on common way to reference OAPI snippets (cf. https://github.com/Schpidi/ogcapi-coverages-1)
- [ ] Resolve all issues on the Core Release project https://github.com/opengeospatial/ogcapi-coverages/projects/1

**Comment by jerstlouis** [comment]
Closing this issue -- we don't need a meta-issue inside the project.
We will address all issues in the Core release prior to the OAB review.
