### ISSUE TITLE
Verify that the document draft is automatically generated

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#125]
https://docs.opengeospatial.org/DRAFTS/19-087.html is out of date

**Comment by cmheazel** [comment]
March 3, 2021, Drafts of both the Standard and Users Guide are generated each evening and stored on https://docs.opengeospatial.org/DRAFTS.  Both HTML and PDF encodings are provided.

The current version of the draft standard is dated August 10, 2020. I'll update the cover page and validate that the draft generated tonight contains that update. If it does, then this Issue will be closed.

**Comment by cmheazel** [comment]
Verified - the updated version was generated.
