### ISSUE TITLE
Statements/Reminders labeled as TODO

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#140]

**Comment by jerstlouis** [comment]
2021-09-08 SWG:

These are the TODOs left:

The follow 2 TODOs were about the unresolved CIS media types / negotiation by profile which we agreed were fine as it is an outstanding topic (https://github.com/opengeospatial/coverage-implementation-schema/issues/19).

clause_8_media_types.adoc:|JSON / CIS JSON|application/json (TODO: either OGC API will adopt a mechanism for negotiation by profile, or a more specific media type will be registered)
clause_8_media_types.adoc:|CIS RDF| application/ld+json (TODO: either OGC API will adopt a mechanism for negotiation by profile, or a more specific media type will be registered)

These TODOs are from modules imported from OGC API - Common - Part 2, and re-used as-is from the resources already defined in Common (list of collections/coverages). The text for these may be simply removed or replaced by a link to the relevant OGC API - Common - Part 2 specifications.

clause_7_geodata_coverage.adoc:*TODO*: Move `geodata-filteredList` conformance class into its own clause, which may end up only in OGC API - Common - Part 2: Geospatial data has Coverage doesn't add anything.
clause_7_geodata_coverage.adoc:*TODO*: Limit and Paged response may apply to both listing collections (`geodata-filteredList`) and the coverage itself.

(it's unlikely that the coverage itself will support paging, as subsetting and re-scaling is as much more convenient way to retrieve part of a coverage).

We may still need to define new bbox and dateTime conformance classes as an alternate query mechanism to the `subset` query parameter. This could re-use the OGC API - Common - Part 2 modules and define them against the new `/coverage`, `/coverage/rangeset`, and `/coverage/domainset` resources.

clause_7_geodata_coverage.adoc:*TODO*: Create new clauses for conformance classes for `coverage-bbox` and `coverage-dateTime` (or potentially make this a single one), which are additional ways to sub-select the actual coverage data being returned that a service may opt to suport.

We can probably get rid of tehse as it's unlikely that the coverage itself will support paging, as subsetting and re-scaling is as much more convenient way to retrieve part of a coverage:

requirements/common-core/REQ_paged-response.adoc:TODO: These Features resources pertained to individual features being returned, and are not currently defined in Common.
requirements/geodata-coverage/REQ_paged-response.adoc:TODO: These Features resources pertained to individual feaures being returned, and are not currently defined in Common.

**Comment by cmheazel** [comment]
The only remaining TODOs require agreement on MIME types for CIS JSON and CIS RDF.

**Comment by jerstlouis** [comment]
SWG 2022-04-06: For now we should replace the TODO by a NOTE that at a point where a solution to perform negotiation by profile, or having successfully registered a media type with IANA, the specification would be updated.

**Comment by cmheazel** [comment]
Done.
