### ISSUE TITLE
Clarify whether spatial extent in collection document should be in CRS84 or storage CRS

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#144]
Consider implications for APIs implementing a future CRS extension or not, for datasets where the coverage is not natively stored in CRS84.

See:

https://github.com/opengeospatial/ogcapi-common/issues/91#issuecomment-894713298
https://github.com/opengeospatial/ogcapi-common/issues/91#issuecomment-894759911
https://gitlab.ogc.org/ogc/T17-D012-Geo-Data-Cube-API-ER/-/issues/22

Also consider that if the collection is available as both _Features_ and _Coverages_, _Features_ requires that the spatial extent be specified in CRS84.

**Comment by jerstlouis** [comment]
SWG 2021-09-22: Members present agree that the following approach would make sense:

- _OGC API - Coverages - Part 1: Core_ would only support the storage CRS
- The `bbox` reported in /collections/{collectionId} extent's spatial would always be in CRS84, allowing a collection to be available as both _Features_ and _Coverages_
- The domainset e.g. at `/collections/{collectionId}/coverage/domainset` would always be in the storage CRS
- OGC API - Coverages - Part 2: (CRS by reference?) would allow to specify a subsetting (subset-crs) and output crs (crs) to change either or both
- We could start putting together a requirement module in Common based on the commonnality between Coverages and Features

@chris-little would this align well with EDR as well?

**Comment by pebau** [comment]
what is called "storage CRS" above is referred to as "native CRS" in the coverage standards.

**Comment by jerstlouis** [comment]
@pebau right, I highlighted that above as `storage/native/default` CRS

In  _[Features Part 2](http://docs.opengeospatial.org/is/18-058/18-058.html)_ it is called storageCRS.
I see _native_ and _storage_ as equivalent here, and we should state that in _OGC API - Coverages_ so that we can re-use the common `storageCRS` member in the collection description, while aligning this with the coverage standards.

_default_ refers to the CRS for the `subset` parameter as well as the CRS for the returned output coverage, when no CRS is explicitly specified (as well as the only CRS supported when the CRS extension is not supported).

What we are saying here is that for _OGC API - Coverages_, the default CRS is the native/storage CRS.
By contrast, in _Features_, the default CRS is always CRS84.

**Comment by chris-little** [comment]
@jerstlouis Of the5 bullet points above, the second 

> The bbox reported in /collections/{collectionId} extent's spatial would always be in CRS84 or CRS84h (regardless of the storage CRS), allowing a collection to be available as both Features and Coverages

is fine, but we will discuss all of them at the next EDR API SWG next week.

Having the same terminology as API-Features is good, as we went for compatibility with both API-Common and API-Features  
where possible.

I am not sure about the implications of the last , fifth,  bullet point, as the Features SWG have already mapped out several successive Parts covering a lot of possible commonality.

**Comment by cmheazel** [comment]
The bbox is now required to be CRS84 or CRS84h

**Comment by nmtoken** [comment]
EPSG:4326 vs CRS84 may be equivalent save lat/long axis order, but what is the EPSG CRS equivalent for CRS84h when we step into a third dimension?

**Comment by jerstlouis** [comment]
@nmtoken [EPSG:4979](https://epsg.io/4979)

**Comment by jerstlouis** [comment]
SWG 2022-06-08: Today we discussed that to unconditionally require CRS84 (strictly talking about for collection spatial extent bbox, not native/storage/access CRS) as implemented in https://github.com/opengeospatial/ogcapi-coverages/commit/a5aab39e629ef2d8a502af54612c81065f0d5b17 might be too exclusive to use cases beyond Earth, and that the current wording of [Requirement 4](https://docs.opengeospatial.org/DRAFTS/19-087.html#collection-resource-definition-section) _"SHALL be interpreted as"_ could perhaps more clearly target the server e.g., "SHALL be **specified** as". We had a [similar discussion](https://github.com/opengeospatial/ogcapi-maps/issues/82#issuecomment-1091863483) in Maps and we should probably address this in Common as well (Currently [in Common - Part 2](http://docs.opengeospatial.org/DRAFTS/20-024.html#collection-extent-section) the CRS84 restriction is only in the extent.yaml schema enum, and mentioned in _Permission 1_).

My suggestion is a requirement that includes conditional text _For geospatial on Earth_. An ETS could still test for CRS84, but it would a justification could be provided for failing the test in the highly unlikely case where an implementation is using non-Earth data for conformance tests. @cmheazel @joanma747.

**Comment by nmtoken** [comment]
I assumed that for data that didn't have any mapping to latitude or longitude or ellipsoidal height, the mandated bounding box would be null, or contain null elements.

**Comment by jerstlouis** [comment]
SWG 2022-06-16: Discussed and recommending that Requirement 4 be changed to:

**For spatial data on Earth**, the coordinates in the bbox schema element SHALL be interpreted as WGS 84 longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) OR WGS 84 longitude/latitude/ellipsoidal height (http://www.opengis.net/def/crs/OGC/0/CRS84h).

**Comment by nmtoken** [comment]
How will a validator know if the data described is "on Earth"?

**Comment by jerstlouis** [comment]
@nmtoken It won't, so that's why I suggested in the [comment above](https://github.com/opengeospatial/ogcapi-coverages/issues/144#issuecomment-1150132212):

> _"An ETS could still test for CRS84, but a justification could be provided for failing the test in the highly unlikely case where an implementation is using non-Earth data for conformance tests. "_

**Comment by nmtoken** [comment]
Not just for formal conformance testing; any client, should have the ability to test whether the response is valid.  

To me too there is a difference between `for Earth` and `on Earth`, the former means any Earth location, the latter implies to me the surface.

I get that a validator could look up a _non-CRS84 CRS to verify whether it is for Earth or another planet_ or indeed non-spatial, but I'm stuck on the logic.

**Comment by jerstlouis** [comment]
@nmtoken "any Earth location" is the intended meaning, therefore _For Earth_.

The logic would require a CRS database, and definitions schemas that enable this.

**Comment by nmtoken** [comment]
The validation logic shouldn't be based on whether the validator has access to a CRS database.

It mustn't be that if no CRS database is accessible to the client, the server must supply a CRS84[h] bounding box.    There should be a 'unworldly' flag &/or nil reason on the bounding box.

**Comment by pebau** [comment]
what cannot be validated is not in the standard. So if Mars data cannot validate, OAPI-Coverages does not support them.

**Comment by jerstlouis** [comment]
@nmtoken 

> There should be a 'unworldly' flag &/or nil reason on the bounding box.

Well that was what my suggestion of _"a separate property indicating a planet or a class of CRS may be useful to address that problem."_ was about. Mars is still a world and hopefully some of us will be living there soon :) Having a separate URI for the planet or CRS class would solve that problem.

However I am not sure we need to go into so much details at this version of the specification. What we want to ensure is not to exclude any use cases right now, while keeping things easy to exdtend in the future.

**Comment by jerstlouis** [comment]
2022-10-05: Fixed by #144.
