### ISSUE TITLE
'conformance' relation type in OGC API - Coverages Landing Page

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-coverages#148]
Requirement 14 B of OGC API - Common says.

The content of that response SHALL be based upon the schema [landingPage.json](https://github.com/opengeospatial/oapi_common/blob/master/core/openapi/schemas/landingPage.json) and include links to the following resources:

* /api (relation type 'service-desc' or 'service-doc')
* /conformance (relation type 'http://www.opengis.net/def/rel/ogc/1.0/conformance')

However, the Landing Page response example in Clause 7.3.1.2 of OGC API - Common - Part 1 shows the relation type as 'conformance'.

@cmheazel @jerstlouis Does the Landing Page response example in OGC API - Coverages need to be updated **OR** is the typo in OGC API - Common?

**Comment by jerstlouis** [comment]
SWG 2022-03-30: This has already been applied.
