### ISSUE TITLE
Review OpenAPI schemas and definitions, linking to external Common ones

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#151]
- Review both Common and Coverages schemas, responses, parameters, and figure out which is out of date. Synchronize as necessary.
- If possible, use external definitions to beta.opengis.net to avoid duplicating the resources in both repositories

**Comment by cmheazel** [comment]
Review and updates are complete. There is a reference to confClasses.yaml which does not resolve. Investigating

**Comment by jerstlouis** [comment]
This issue broke the OpenAPI definition.
We also clarified that we should not be using beta.opengis.net for draft specifications.
The schemas here were also much more recent, with a modular reorganization based on the work in OGC API - Tiles and. This was broken by this commit, so suggesting that we partially revert this commit, as done in PR #168.

**Comment by jerstlouis** [comment]
SWG 2022-07-27: PR #168 fixes the broken API definition. Further synchronization efforts with Common and other API specifications would involve trying to maintain the same directory structures. Schemas could be identical (Unless an API suggests a common backward-compatible extension), and could be automatically regularly compared for differences between the different specs and Common. Other API building blocks such as responses and parameters might slightly differ, as these are an example API definitions and might be tailored for the purpose of illustrating the target specification (e.g., the conformance response would list the relevant conformance classes, the f parameter would list the relevant formats). Cross-SWG discussions could happen in OGC API - Common SWG or another forum to discuss bringing in new building blocks from the different API specs into _Common_ specifications.
