### ISSUE TITLE
UAD extent

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-coverages#153]
Should we add support for the Uniform Additional Extent to the collection information?  Is it mandatory or a separate requirements class?

**Comment by cmheazel** [comment]
UAD Extent is currently required for all API-Collections implementations. This would not be a problem if the schema is a proper extension to the Extent schema defined in Common. This needs to be verified.

**Comment by jerstlouis** [comment]
Coverages now has a requirement on UAD extent, including the `grid` property allowing to describe regular and irregular grids, and the requirements allowing to describe sparse intervals as additional following the first "overall" lower and upper bound of a dimension (exactly as with "temporal"). The UAD requirements would automatically apply to collections with an [ogc-rel:coverage] link.

I suggest that we also define a requirement class in Common - Part 2 specifying which would specify that it applies to all collections of the API. cc. @joanma747
