### ISSUE TITLE
Reuse Subset Requirements Module

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-coverages#154]
Should we use the "subset" requirement module for all subsetting operations?
coverage subset uses the subset parameter
domainset subset defines a subset parameter identical to that of coverage subset, but adds some domainset specific requirements
rangset subset defines a separate parameter. However it could also be represented using the subset parameter:
    Subset=RED  (Point=bandName)
    Subset=5    (Point=bandIndex)
    Subset=5000:10000  (Interval = low:high frequency)

**Comment by jerstlouis** [comment]
SWG 2022-02-23: We have agreed to #157 (change range subsetting parameters to `properties`), which will clarify that this is not related to the `subset` capability and make this more accessible to general web developers. Specification will be corrected accordingly.
