### ISSUE TITLE
Scenes requirements class

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#171]
As proposed in [Testbed 17 GeoDataCube API Engineering Report](https://docs.ogc.org/per/21-027.html#toc24) (_5.2.6 Scenes API_), it would make a lot of sense to define an optional requirements class for listing the individual component scenes of a coverage (e.g., LANDSAT scenes), retrieving metadata for each of the scenes, filtering them based on metadata such as a maximum cloud coverage, time and area of interest, (similar to STAC and ideally based on the _OGC API - Records_ [Local Resource Catalog](https://github.com/opengeospatial/ogcapi-records/issues/300) concept where in this case the resource is the scenes) retrieving a coverage for each of them as well as the description of their domains.

By making the `../coverage` resource not tied specifically to `/collections/{collectionId}`, we could easily support `/collections/{collectionId}/scenes/{sceneId}/coverage` for retrieving the coverage of an individual scene.
The JSON schema for `/collections/{collectionId}/scenes/{sceneId}` would include an `extent` property just like the one at `/collections/{collectionId}`, plus additional scene-specific record fields such as those defined by STAC / Records.

Both `/collections/{collectionId}/scenes` and `/collections/{collectionId}/scenes/{sceneId}` would be modeled after the Records _Local Resource Catalog_ concept.

**All scenes of a coverage would share the same RangeType / Schema of observed/measured fields/properties.**

The individual scenes of a coverage may have a different native CRS than the overall coverage e.g., each scene may be in a particular UTM grid whereas the overall coverage is available in WGS84. This requirements class would enable some of the use cases that the more complex multi-part CIS coverages addressed.

This requirements class could be either included in Part 1 or in a Part X extension.

The `/collections/{collectionId}/scenes/` could also be where a CRUD extension for _Coverages_ allows adding/updating/deleting individual scenes as explored in the [Testbed 15 "Images API"](https://docs.ogc.org/per/19-070.html).

This extension could also be supported as a building blocks for other specifications such as _Maps_ and _Tiles_ (of a particular scene), and even potentially extended to feature collections organized in separate component parts.

**Comment by jerstlouis** [comment]
@chris-little I have not fully understood the concept of instances yet in EDR (despite really trying to), but according to that definition you just quoted, definitely not.

Different scenes are not different _views_ on the same collection, but different **_components_** of the collection.

That is the coverage consists of the function that provides values for a direct position for any position with each of the component scenes.

Scenes does not imply anything specific to a visual representation.
Scenes is the term used for example by the [Landsat data products](https://www.usgs.gov/landsat-missions/landsat-data-access#C2L2).

**Comment by chris-little** [comment]
@jerstlouis Think of instances as versions, which are usually different components but with some common metadata. E.g. draft, 2nd draft, final versions of some data,;or uncalibrated or calibrated; or test, development or production.

The bbox of the collection instances/components would be the same, andthe instances metadata could be queried just like the collection metadata.

Is that the same as scenes?

**Comment by jerstlouis** [comment]
@chris-little Not exactly the same as scenes.

The bbox and/or the datetime of each scene is different.

There is this similar concept that the metadata of each scene could be queried -- even as part of a coverage request filter, even together with the individual cell ("pixel") values.

The most important distinction I believe is that with scenes it is meaningful to put all of those scenes together to return a coverage such as by doing a mosaic and filtering out clouds.

With your concept of instance, if I understand correctly you would never want to mix multiple "versions" together to return all of the data together. They are like the different experiment runs, or the different forecasts started from different observation times or for a different time period.

However, I agree that we could have shared concepts that apply to both.
For sure the [Local Resource Catalog requirements class](https://github.com/opengeospatial/ogcapi-records/issues/300) of _Records_ would cover a lot of that:
- having a list of resources (`/collections` or `/collections/{collectionId}/scenes` or `/collections/{collectionId}/instances`),
- having individual resources (`/collections` or `/collections/{collectionId}/scenes/{scene}` or `/collections/{collectionId}/instances/{instanceId}`)
- having core and resource-specific record fields that can be queried and being able to use `filter=` expressions to filter the list of resources

Something else that might be shared is the data access point for a specific instance or scene:
- `/collections/{collectionId}/coverage`, `/collections/{collectionId}/scenes/{sceneId}/coverage`, `/collections/{collectionId}/instances/{instanceId}/coverage`
- `/collections/{collectionId}/cube`, `/collections/{collectionId}/scenes/{sceneId}/cube`, `/collections/{collectionId}/instances/{instanceId}/cube`

In this sense, I am considering that the `../coverage` resource may not necessarily be tied to the `/collections/{collectionId}` resource (like the `../map` and `../tiles` resources in _Maps_ & _Tiles_).

When you have instances in EDR, what does `/collections/{collectionId}/cube` return? a default instance, or composite of all instances together?

**Comment by chris-little** [comment]
@jerstlouis Thanks for the explanation of the differences. If there are instances in a collection, it is up to the service provider to decide what is returned: nothing/error condition, a default instance or possibly all instances (but the latter is not really  recommended, as we are trying to reduce data volumes!)
We are considering an OGC API-EDR Part 3 which could do summary stats and/or aggregation which might be a standardised way of addressing the latter use case.

**Comment by jerstlouis** [comment]
@chris-little I hope we can consider alignment for aggregation, at least the aggregation functions and their meaning.
We are also looking at the aggregation functions defined by WCPS and openEO.

**Comment by cnreediii** [comment]
@jerstlouis Not to be picky, but is `scene` defined somewhere? Not in the TB 17 ER. I ask because QGIS, GDAL, Esri, etc all use 'scene' in reference to a "symbolized geospatial content that allows you to visualize and analyze geographic information in an intuitive and interactive 3D environment". This is different than a Landsat scene. Should have a definition to avoid confusion.

**Comment by jerstlouis** [comment]
@cnreediii For sure we need to clarify the meaning, and add _scene_ to the terms and definition in this particular context. Thanks for pointing this out!

**Comment by chris-little** [comment]
@jerstlouis Further to my comment last week, as API-EDR `Instances` are like `Collections`, they can have the full gamut of extents, values/parameters, CRSs, etc exactly like a `Collection`, so I still think there is a strong overlap with `Scenes`. In particular, we envisaged a specific query, or whatever type and extent, time, parameters may be repeated against a different `Collection` or `Instance`, and therefore could be stored as an `Item` (it is an abstract potential feature of interest) This seems to have commonalaity with 'Scene' too.

**Comment by jerstlouis** [comment]
@chris-little A specific requirement of Scenes here is that they share the same _fields_ (that you call value/parameters in EDR) as the collection. But yes there is commonality.
