### ISSUE TITLE
Organization of a February 2024 OGC API - Coverages Virtual Code Sprint

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-coverages#176]
The SWG discussed today that there would be interest in hosting a 3 days virtual code sprint for OGC API - Coverages in February 2024, tentatively the week of the 12th.

The effort would continue the good implementation momentum from Testbed 19 GDC API Technology Integration Experiments, and provide validation for the latest OGC API - Coverages candidate standard, which we hope will be in the Request for Comments period at that time.

This will be a SWG Code Sprint, organised by SWG Members, and open to the general public. 

- [X] SWG/DWG Chair identifies a date for the code sprint. **The code sprint will be held from Tuesday, February 13th to Thursday, February 15th, 2024.**
- [X] SWG/DWG Chair identifies a mode for the code sprint, if it is to be a hybrid event. **This will be a virtual-only code sprint.**
- [X] At least 3 months before the envisioned event date, the SWG/DWG Chair submits an Event Request to the OGC Event Manager.
- [X] OGC Staff discuss the proposed sprint schedule and together deconflict the event from other OGC event
- [x] OGC Staff confirm the dates have been reserved for the code sprint
- [X] SWG/DWG Chair identifies SWG Member to serve as SWG Event Organizer. **Jerome St-Louis** confirmed as the SWG Event Organizer.
- [x] SWG Event Organizer prepares initial draft announcement for Press Release.
- [x] OGC DPM adds the Sprint to the OGC API Website (if sprint involves OGC APIs).
- [x] SWG Event Organizer populates the GitHub wiki page on the developer-events repository.
- [x] SWG Chair reviews and approves the announcement for Press Release .
- [x] OGC DPM or DevRel reviews and approves the announcement for Press Release.
- [x] SWG Event Organizer prepares registration page on the ogcapi-coverages GitHub repo
- [x] SWG Event Organizer confirms communication platforms for the event. .
- [ ] SWG Event Organizer sends out 1st notification to participants, with logistics details (one month before sprint)
- [ ] SWG Event Organizer sends out 2nd notification to participants, with logistics details (two weeks before sprint)
- [x] SWG Event Organizer sends proposals for social media posts to the OGC Communications Manager (two months before)
- [ ] All SWG members spread the word about the event among their contacts
- [ ] SWG Event Organizer sends out Final notification to participants, with logistics details (1 day before sprint)
- [ ] Hold the Sprint event

**Comment by jerstlouis** [comment]
cc. @ghobona @tomkralidis @pebau @pomakis

**Comment by ghobona** [comment]
The OGC API - Coverages Virtual Code Sprint would have to be before 26 February to avoid clashing with the next Joint OGC ASF OSGeo Code Sprint.

**Comment by jerstlouis** [comment]
@ghobona Yes this is why we picked the week of the 12th.

**Comment by ghobona** [comment]
@jerstlouis I have just connected you with OGC's Event Manager via email so that the dates can be checked for calendar conflicts.

**Comment by ghobona** [comment]
@jerstlouis Here is a example announcement from the OGC API - Processes Virtual Code Sprint https://www.ogc.org/press-release/developers-invited-to-the-2023-ogc-api-processes-virtual-code-sprint/

**Comment by jerstlouis** [comment]
Thanks a lot @ghobona we'll start with that.

Hoping to make progress on some of the other _SWG Event Organizer_ items as well today.

**Comment by ghobona** [comment]
The Press Release has been announced. https://www.ogc.org/press-release/developers-invited-to-the-february-2024-ogc-api-coverages-virtual-code-sprint/

**Comment by ghobona** [comment]
LinkedIn post https://www.linkedin.com/feed/update/urn:li:activity:7158122139424874496?utm_source=share&utm_medium=member_desktop

**Comment by ghobona** [comment]
Another LinkedIn post https://www.linkedin.com/posts/open-geospatial-consortium_ogcapi-webapi-standard-activity-7158144876532944896-uIyB?utm_source=share&utm_medium=member_desktop

**Comment by doublebyte1** [comment]
@jerstlouis I tried to add myself to the wiki page [here](https://github.com/opengeospatial/ogcapi-coverages/wiki/February-2024-OGC-API-%E2%80%90-Coverages-Virtual-Code-Sprint#registration), but I don't have write permissions on this repo. Not sure if anyone else who is not a committer here, tried to register.
