### ISSUE TITLE
Reference definition of Sensor Model from ISO 19130-3:2022

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-coverages#177]
[ISO 19130-3:2022](https://www.iso.org/obp/ui/en/#iso:std:iso:ts:19130:-3:ed-1:v1:en) offers a definition of 'sensor model' that could be referenced by OGC API - Coverages.

Currently OGC API - Coverages offers its own definition in [Clause 4.8](https://docs.ogc.org/DRAFTS/19-087.html#_sensor_model).

**Comment by jerstlouis** [comment]
Suggesting to change the Sensor Model definition to the ISO 19130-3:2022 definition:

> mathematical description of the relationship between the three-dimensional object space and the 2D plane of the associated [image (3.2)](https://www.iso.org/obp/ui/en/#iso:std:iso:ts:19130:-3:ed-1:v1:en:term:3.2) produced by a [sensor (3.5)](https://www.iso.org/obp/ui/en/#iso:std:iso:ts:19130:-3:ed-1:v1:en:term:3.5)

cc. @alexrobin @cmheazel is that OK?

**Comment by alexrobin** [comment]
I like the fact that the definition from ISO19130 is more formal than the one currently in the document.

Unfortunately, the reference to a "2D plane of the associated image" makes it specific to imaging sensors, which is somewhat restrictive for coverages in general... I think you might want to associate other types of sensor models to coverages, such as the ones of LiDAR, profilers, etc...

**Comment by alexrobin** [comment]
@jerstlouis I like your definition, although I wonder if we should be more specific and call it the "geometric sensor model", as there are other aspects of a sensor model such as the "radiometric model", or more generally the "response model", which is linked to the range of the coverage.

**Comment by jerstlouis** [comment]
The changes have been applied and no further feedback was received so so closing this issue.
