### ISSUE TITLE
Variables in the URL template are case-sensitive

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-coverages#23]
The https://tools.ietf.org/html/rfc6570 says:
"Variable names are case-sensitive because the name might be expanded within a case-sensitive URI component."
This means that coverageid is not the same as coverageId.
I request that OGC API coverages uses lowerCammelCase for path variables.

I'm not able to find any reference to "case" in the definition of the key in a KVP "query" part (known as application/x-www-form-urlencoded)". Actually, https://www.ietf.org/rfc/rfc3986.txt says that the query string is case-sensitive. "The other generic syntax components are assumed to be *case-sensitive* unless specifically defined otherwise by the scheme (see Section 6.2.3)." If somebody is able to find a RFC that says that, please tell me.

It seems that OGC introduced in OWS Common 1.0 "11.5.2  Capitalization" : "The capitalization of parameter names when KVP encoded shall be case insensitive, meaning that parameter names may have mixed case or not. EXAMPLES   The “request” parameter name could be REQUEST, request, Request, or ReQuEsT."

**Comment by Schpidi** [comment]
In #11 we decided to use all lower case https://github.com/opengeospatial/ogc_api_coverages/issues/11#issuecomment-502845550

**Comment by cmheazel** [comment]
Action to CMH - make sure all URL templates are lower case.

**Comment by jerstlouis** [comment]
@joanma747 actually here https://stackoverflow.com/questions/24699643/are-query-string-keys-case-sensitive it is clarified that query string keys are in fact case sensitive.
See also https://github.com/opengeospatial/oapi_common/issues/42 .

**Comment by pebau** [comment]
common practice, for all that I know, is that GET keys are all-uppercase; values are case-sensitive anyway.

**Comment by jerstlouis** [comment]
@pebau In OWS, keys were case-insensitive and all-uppercase were commonly used.

The approach (as discussed in issue above) in OGC API is that it is case-sensitive, and the convention is camelCase.

**Comment by Schpidi** [comment]
> The approach (as discussed in issue above) in OGC API is that it is case-sensitive, and the convention is camelCase.

actually, I thought we agreed to use all lower case in #11 as referenced above?

**Comment by jerstlouis** [comment]
@Schpidi camelCase is what was agreed in Common (https://github.com/opengeospatial/oapi_common/issues/42). It makes it more readable to separate words.
My vote would be camelCase, for both consistency with Common (especially if some parameters will end up in common, it would be very confusing to have different conventions) and readability. If the SWG already decided on lower case, we may not want want to re-open the issue now, but the mismatch with the OGC API family may come up later in reviews...

**Comment by Schpidi** [comment]
@jerstlouis camelCase like `datetime` and `bbox` in https://github.com/opengeospatial/oapi_common/blob/master/collections/clause_8_collections.adoc#2-parameter-requirements or `bbox-crs` in https://github.com/opengeospatial/oapi_common/blob/master/crs/standard/clause_6_crs.adoc#query :thinking:

**Comment by Schpidi** [comment]
Coverages SWG call: The SWG asks for guidance from the naming authority on the punctuation of paths and parameters. Can you please add a comment here @ghobona? Thanks

**Comment by jerstlouis** [comment]
See updates from Common in
https://github.com/opengeospatial/ogcapi-common/issues/131
https://github.com/opengeospatial/ogcapi-common/issues/158

where it was agreed that the servers are allowed some leeway in accepting the non-official casing, and where either camelCase or dash separation can be chosen by a given standard.

**Comment by jerstlouis** [comment]
2020-12-23: We suggest to use kebab-case for OGC API - Coverages (e.g. scale-size), following the OGC API - Features example.

**Comment by KathiSchleidt** [comment]
Is there any agreement within OGC on casing? I've seen all variants from kebab-case over snake_case to ?necklace.case?, and of course the occasional dinosaur such as myself still stuck in camelCase...
Is there any common agreement here (I know some tools have some issues with some variants ;) ), or just the agreement to disagree and get on with other stuff?

**Comment by tomkralidis** [comment]
+1 for kebab-case

**Comment by Schpidi** [comment]
Coverages SWG: Agreed to use kebab-case unless there is different guidance from the naming authority.

@tomkralidis offered to recommend kebab-case to EDR

**Comment by tomkralidis** [comment]
FYI EDR API has now been updated to support kebab-case (https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/170 / https://github.com/opengeospatial/ogcapi-environmental-data-retrieval/issues/172).

**Comment by ghobona** [comment]
@Schpidi Since this issue has been resolved through the kebab-case approach, I recommend that the Issue is closed at the next telecon.

**Comment by Schpidi** [comment]
Coverages SWG call: Thanks @jerstlouis for implementing the change.
