### ISSUE TITLE
Coverage with common and OpenAPI definition

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-coverages#26]
Please take a look at the work done here:
https://github.com/opengeospatial/OGC-API-Map-Tiles

where we are considering a OGC API common to support maps, tiles, coverages and features.

This is the common OpenAPI "domains" document:
https://github.com/opengeospatial/OGC-API-Map-Tiles/blob/master/standard/openapi/ogc-api-common.yaml
This is the OpenAPI "domains" document for coverages
https://github.com/opengeospatial/OGC-API-Map-Tiles/blob/master/standard/openapi/ogc-api-coverages.yaml
This is an example of coverage service described with OpenAPI and using the last two documents as building blocks
https://github.com/opengeospatial/OGC-API-Map-Tiles/blob/master/standard/openapi/ogc-api-map-tiles-opf-xmp-ct-more-1-collection.yaml

the CIS schemas are still not include as part of the Coverage API part.

**Comment by Schpidi** [comment]
@joanma747 could you please update the links if this is still valid or close otherwise? Thanks

**Comment by Schpidi** [comment]
Coverages SWG call: Seems the files have been moved to https://github.com/opengeospatial/ogcapi-tiles/tree/master/openapi/swaggerHubUnresolved.

Here is an approach trying to use all elements by reference instaed of duplicating them: https://github.com/Schpidi/ogcapi-coverages-1/tree/master/yaml-unresolved.

@joanma747 would you be willing to join one of the coverages group calls on Wednesdays to discuss this?

**Comment by jerstlouis** [comment]
@Schpidi We discussed this with @joanma747 in the _Tiles_ SWG last week, and OGC API specifications should follow a standard paths layout for OpenAPI schemas, allowing to reference the YAML schema file on the repository it belongs, e.g.

"$ref" : https://github.com/opengeospatial/ogcapi-common/blob/master/collections/openapi/schemas/collectionInfo.yaml

until the specifications are released and the schemas are published on opengis.net (at which point the references will be updated).

**Comment by Schpidi** [comment]
Latest version of the schemas for discussion is available in the [schema-work](https://github.com/opengeospatial/ogcapi-coverages/tree/schema-work) branch. Thx @jerstlouis for your help!

**Comment by jerstlouis** [comment]
2021-07-28: The OpenAPI definitions from schema-work branch are merged into master. We discussed how the beta.schemas.opengis.net could potentially help in referencing external specifications still under development (see https://github.com/opengeospatial/coverage-implementation-schema/issues/17). We will continue the discussion in OGC API - Common.
