### ISSUE TITLE
Tiled coverages (to populate a GeoPackage or else).

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/ogcapi-coverages#27]
Hi,

It occurred to me that if could be good to specify a way to obtain tiles from a (grid) coverage. A common use case is to populate a GeoPackage. GeoPackage has defined "elevation" tiles that has the data in them (not a pictorical representation but real elevation numbers).

By combining coverages with tiles we could create a path like this:
'/collections/{collectionId}/coverages/{coverageId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}':
that allows access to a particular tile in a coverage.

We are using the same mechanims also for tiled features and tiled maps so it might be interesting to have coverages also on board. I know you will say that you already have a "subset" mechanism. WMS also had a subset (BBOX) but i was useful to specify go to get tiles without caring so much in BBOXes (or caring only once; while defining the TileMatrixSet).

**Comment by pebau** [comment]
OGC CIS 1.1 offers a conformance class coverage-partitioning which describes tiled coverages, among others.

**Comment by joanma747** [comment]
Sure but, is it the same tiling?

One thing is to have coverages partitioned in pieces that are smaller than a too huge coverage (we call it sheets in Orthophotography or 'granules' in Sentinel 2) and another thing is to get back coverages as small tiles like in WMTS but instead of a picture (jpeg) but in geotiff (or similar) following a tileMatrixSet.. 

The latter is what can be used to populate a GeoPackage.

If you believe the case is covered by CIS 1.1 or WCS lets forget about it, but I find the idea interesting and parallel to the so called "vector tiles" (tiles that are not pictorical but contain geometries).

**Comment by pebau** [comment]
your question is appropriate indeed - CIS does not prescribe one tiling for all (in particular not: storage and delivery, as it is service agnostic) - it is just an encoding, a representation. As such, I see its main use in delivery indeed, as storage should remain agnostic to allow implementers to do all their magic. For example, the rasdaman API allows specifying independent storage mechanisms (tiling, compression) for tiles stored vs tiles delivered as query results. WCS currently does not have an option of specifying output tiling, would be interesting and useful to have.

So GeoPackage might consider CIS 1.1 for storage of tiled coverages, thereby getting compatible with other coverage handlers in the OGC ecosystem. That was the only thing I wanted to express, sorry for the confusion.

**Comment by jerstlouis** [comment]
@joanma747 the latest version of the specifications makes this easy.

Subsetting and Scaling are conformance classes of Part 1: Core, and one can subset beyond the coverage extent allowing to retrieve partially filled tiles. Server returns 204 if there's no data for a tile (so the client doesn't waste resource writing empty tiles).

**Comment by Schpidi** [comment]
Coverages SWG Call: Agreed to add a note about OGC API - Tiles usage but not put it in normative text.

**Comment by Schpidi** [comment]
Coverages SWG call: Agreed to write a non-mandatory conformance class to support tiles (see also https://github.com/opengeospatial/ogcapi-maps/issues/56#issuecomment-756241354). Depending on the status of the tiles API this might or might not be part of core.

**Comment by jerstlouis** [comment]
Addressed by #122
