### ISSUE TITLE
Subsetting RangeSet

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-coverages#45]
Should we support subsetting of the RangeSet. A subset operation on the RangeSet would only return content from the RangeSet
Related issue: #30

**Comment by pebau** [comment]
we are mixing concerns here: functionality vs result format. 
- Subsetting is only defined on coverages, not its constituents (and what if the coverage is given not by domain and separate range, but by coordinate/value pairs etc?). 
- Format encoding can be chosen independently; the case mentioned ("only content from range set") could be resembled, eg, by a PNG result.

Let me suggest to reuse the mechanism of CIS/WCS that says: all information that can be represented in the output format is squeezed into the file, specified in one spec (or conformance class[es]) per format. That information may be complete or incomplete, depending on the individual format, but users are aware as they requested it explicitly: if I choose JPEG I know I will not get range type nor domain set, if I choose JSON or NetCDF I know I will get it. WCS also has mechanisms for the case that informational completeness should be coupled with efficient binary formats by using containers like MIME attachments, zip, etc.

Advantage: we keep it simple by having all operations working uniformly on coverages.

**Comment by Schpidi** [comment]
Coverages SWG call: Current draft defines subset on a coverage as suggested.
