### ISSUE TITLE
If coverage is chunked or stored in objects, how does that scheme get advertised?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-coverages#51]
Is there a "tiling" access mechanism in the case that the data is broken up into objects or chunks?

**Comment by Schpidi** [comment]
I was hoping to being able to plug the /tiles path from OGC API - Maps & Tiles under /coverage to achieve this.

**Comment by pebau** [comment]
it is one of the user-centric features of WCS that users do not need to worry about tile boundaries (like with old-school file services), but see seamless objects instead ("from files to pixels"). For those who do not want to use this service quality there are considerations for (2D) tiling indeed, as Stephan mentions.

**Comment by Schpidi** [comment]
Great, so we agree on the best practice to use paths like `.../coverage/tiles/...`. I suppose this could be captured in a Best Practice document. Maybe in OAPI Common as it touches multiple OAPIs?

**Comment by pebau** [comment]
hm, it's not a "best practice" in the sense that anyone has done this with distinct advantages. Also, I just mentioned "considerations", would not necessarily agree to it.

For now, we tend to have coverage/rangeset, coverage/tiles, coverage/metadata, coverage/all, coverage/description... pure confusion IMHO. What about cleaning up coverages/xxx first, which is on the agenda anyway following sprint comments?

**Comment by Schpidi** [comment]
Please open separate issues for separate discussions if you find it worth having them.

**Comment by jerstlouis** [comment]
In #27 we agreed to add tiled coverage conformance class.
Suggesting we can close this issue.

**Comment by jerstlouis** [comment]
SWG 2021-02-10: Agreed to close this issue as we will add a conformance class for tiled coverage in #27.
Testbed 17 will also look at the use of Cloud Optimized GeoTIFF and possibly how it could be used as a backend for the Coverages API (possibly with Coverages Tiles).
