### ISSUE TITLE
Link to OGC DRAFTs build of spec?

### ISSUE THREAD

**Issue by dblodgett-usgs** [opengeospatial/ogcapi-coverages#62]
Looks like API-Coverages is built nightly here: http://docs.opengeospatial.org/DRAFTS/ under: http://docs.opengeospatial.org/DRAFTS/19-087.html

Could someone add a link to this build to a prominent place in the repository? Some have used that draft as the main link at the top of the repo -- otherwise a prominent block at the top of the README?

Maybe I'm just not seeing the link?

**Comment by Schpidi** [comment]
I don't have sufficient rights to change the top main link, maybe someone else can do this.

For now I added a link at the end of the first section of the README.

**Comment by dblodgett-usgs** [comment]
@gbuehler -- who has admin on the repo to add that URL?

**Comment by jerstlouis** [comment]
Done at the top of README.md in edd1a844b5d404d1d6ff8ac4e649b160d15419d7 for now.

**Comment by Schpidi** [comment]
@gbuehler could you maybe add a link to https://ogcapi.ogc.org/coverages in the About section? Thanks

Closing this as we have the link at the top of the README now.

**Comment by ghobona** [comment]
@gbuehler I will create a Trello ticket for all OGC API repos regarding the About section.
