### ISSUE TITLE
rename this repository

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-coverages#68]
For consistency with other OGC API standards, suggest renaming this repository to:

https://github.com/opengeospatial/ogcapi-coverages

Description: An open standard for querying coverage information on the web.

Website: should be URL to draft spec being autogenerated (nightly)?

**Comment by ghobona** [comment]
Please wait. We are drafting an OGC-NA policy on the naming of OGC API repos.

**Comment by jerstlouis** [comment]
The OGC-NA [policy](https://portal.ogc.org/files/?artifact_id=94196&version=1) has been approved and the new name of the repo shall be *drum roll*:

`ogcapi-coverages`

**Comment by Schpidi** [comment]
Please @ghobona could you apply this change? It seems I don't have the rights to do it myself. Thanks

**Comment by jerstlouis** [comment]
The repository has been renamed to `ogcapi-coverages`
