### ISSUE TITLE
How will Coverage Processing be supported?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-coverages#80]
It is foreseeable that a future extension of OGC API - Coverages may offer coverage processing capabilities similar to those offered by WCPS.

So what would such an extension look like?

Please coordinate with the OGC API - Processes SWG on this.

**Comment by pebau** [comment]
@ghobona seems like a low-hanging fruit:
https://github.com/opengeospatial/ogc_api_coverages/blob/master/extensions/processing.adoc

**Comment by jerstlouis** [comment]
@ghobona @bpross-52n @Schpidi

In the previous issue ( https://github.com/opengeospatial/ogc_api_coverages/issues/79 ) which is exactly about this, I propose that this can nicely integrate with OGC API processes, e.g. as a process at `.../processes/wcps` that specifies that one of its input is WCPS code.

Also considering uploading WCPS code as a deployment method (called Processes transactional right now, though I really think the name transaction is miused and it should be `deployment`) to create a specific process.

This integration to act upon different data source would require substitution capabilities which we are investigating as part of our Modular OGC API Workflows project.

**Comment by nmtoken** [comment]
I'm not sure why you would have _.../processes/wcps_ (or expanding the acronym _.../processes/web_coverage_processing_service_)  it's not like there's _.../processes/wps_  

That doesn't seem like integration of WPS and WCPS into a single form.

**Comment by jerstlouis** [comment]
@nmtoken Well the idea is that processing is a general concept for generic processing, while a WCPS process (integrated within that generic processing framework) would be able to perform processing on coverages, with code supplied in a specific WCPS language as a parameter. As I mentioned, a service could also potentially be able to create a number of different processes by uploading WCPS code.

**Comment by nmtoken** [comment]
@jerstlouis but it could be integrated 

`POST /processes/{process-id}/jobs`   

_Executes a process, i.e. creates a new job. Inputs and outputs will have to be specified in a JSON document_

like:

    {
	"q": "for $c in (ERA5 - cube), $d in (DEM) return encode($c.temperature > 20 and $d > 100, 'image/png')"
    }

**Comment by jerstlouis** [comment]
@nmtoken The integration is the idea, yes.
But `/processes` should still be a generic OGC API - Processes end-point that vanilla OGC API - Processes clients can use, but learn that they need to pass a WCPS query in one of the inputs.

I see both processes at `/processes/{processId}` as being defined by specific (but parameterizable) WCPS code, as well as a generic WCPS runner process e.g. at `/processes/wcps`.

**Comment by pebau** [comment]
Maybe we are seeing two perspectives here:
- WCPS, being part of the WCS suite, is a _data_ service: derive data from data in a flexible way. Hence - and this fits the RESTful paradigm - it is aka "modifier" to coverage data sets (where "data set" is understood in the most general way, no particular definition assumed)
- WPS capitalizes on the processing aspect (which is abhored by REST for all that I know), making algorithms first-class citizens.

IMHO Jerome has shown a way forward by seeing WCPS as one class of algorithms that can be offered via the WPS protocol, in addition to the pre-existing view. This to me induces a natural view of WCPS as an OAPI-Coverages extension (is planned already, actually) _plus_ an embedding in WPS.

This also reflects past work: WPCS is industrially offered via WCS, and a WPS binding has been done earlier. So we know it works :)

**Comment by jerstlouis** [comment]
@pebau 
Regarding WCPS being a data service, while it is true that it allows to access specific data via sub-setting/slicing/trimming/scaling of the data, most of that should be doable with conformance classes outside of the _OGC API - Coverages - Processing_ extension (e.g. through query parameters). When doing more advanced processing and modifications, WCPS really starts being more of a processing service than a data service, and I think it could really shine as such, especially if it embeds well within _OGC API - Processes_ (and considering untying WCPS queries from specific data layers and data ranges via parameterization, and the whole modular workflows magic).

> This to me induces a natural view of WCPS as an OAPI-Coverages extension (is planned already, actually) plus an embedding in [OAPI-Processes].

Yes, exactly, but that _OGC API - Coverages_ extension for processing could potentially have a very light dependency on the very core of OGC API - Processes (i.e. simply a link to `/processes` from the landing page, and in there a link to that generic WCPS process where one can submit WCPS code). With almost no effort this could make it readily usable in clients implementing _OGC API - Processes_, and paves the way for the implementers should they wish to implement _OGC API - Processes_ more in depth (e.g. process description etc.).

**Comment by pebau** [comment]
@jerstlouis The data view we should not give up while exploring how to make it also available via WPS.  One way to easily marry both is that, based on the OAPI-Coverages definition, there is a conformance class in OAPI-Processes which says "/processing/wcps?q=X" is equivalent to "/collections?q=X". That would be the most lightweight thing I could think of.

**Comment by ghobona** [comment]
Due to the need to keep **Part 1: Core** specifications simple enough for the basic developer to use, it would be advisable to plan for an *OGC API - Coverages - Part 2: Processing* that specifies how to use a Coverage Processing Language (CPL) which would be a renaming of WCPS.

**Comment by jerstlouis** [comment]
@pebau I really don't think `/collections?q=X` is appropriate, because doing a GET on that resource should always return you a listing of collections|coverage|geospatial data. A GET on that resource should not be used to do processing and return results instead, and passing large piece of WCPS code as a query parameter is really not ideal. POSTing the WCPS code to `/processing/wcps` could offer you that exact same functionality instead. But I am curious to hear what others think.

@ghobona I agree that WCPS is more of a processing language than a service. A service supporting queries in the language is a service :)

**Comment by pebau** [comment]
@ghobona  I would strongly object to renaming. WCPS must remain WCPS. (Remember the confusion that had been caused by WMS flipping default coordinate sequence.) As we talk about _extensions_ implementers anyway can freely choose what to support. And renaming would not make it simpler to implement.

**Comment by pebau** [comment]
@jerstlouis WCPS GET is working flawlessly. If it is to be constrained in a WPS environment, that's a decision of the WPS carrier protocol. But for the OAPI-Coverages, why should we constrain. 

And I am absolutely sure that I would immediately loose overview on how to use the API if now functionality depends on GET vs POST or ..., it would explode complexity.

**Comment by Schpidi** [comment]
20200914: Coverages SWG: Discussion resulted in this proposal:
- `/wcps` for sending WCPS encoded GET requests and getting the evaluation result.
- `/processes/wcps` for using the vanilla OAPIProcesses approach

**Comment by pebau** [comment]
friendly amendment:

* `/wcps` could also be POST or SOAP etc, not necessarily only GET; critical is: request returns evaluation result
* `/processing/wcps` should, as I understand discussion, be able to host any number of (possibly parametrized) queries in a WPS manner, how can this be invoked? Options might include: allow other names than `wcps`, or allow sub-paths.

**Comment by jerstlouis** [comment]
@pebau regarding `/processes/wcps`, the idea was this could work with either the core OGC API - Processes, or the Modular OGC API Workflow extension approach (or a server could support both).

In both cases, the user could either supply the WCPS code along with the request, or deploy WCPS code as a specific process at an arbitrary `/processes/{processId}` end-point.

If supplying the WCPS code along with the request, the parameterizable WCPS code is one of the inputs of a [process execution document](https://github.com/opengeospatial/wps-rest-binding/blob/master/core/openapi/schemas/execute.yaml), and input data can be provided as additional inputs. If the WCPS code is instead deployed as a process, then one would do a PUT on `/processes/{processId}` with parameterizable WCPS code.

With core Processes, the execution document is submitted as a POST request to `/processes/{processId}/jobs`, and in `sync` mode the output is returned right away, or in `async` a job is created and can be polled, or a URL can be provided as a callback.

In the [MOAW Workflow extension](https://app.swaggerhub.com/apis/jerstlouis/MOAW/MOAW-0.2) approach, depending on the path used either the workflow is set up in a deferred manner, in which case a description document is returned (e.g. for `/processes/{processId}` a collection/coverage description document with the various links to domain set, range type, coverage which can be accessed with subset / scaling etc.), or in the case of a synchronous path data is returned right away and parameters for subset/scaling can be included already with the request (e.g. for `/processes/{processId}/coverage`).

**Comment by pebau** [comment]
@jerstlouis ok, I see you have a solution in mind already. Let me suggest to have the plain /wcps part in the OAPI-Cov section and the /processing/wcps in the OAPI-Proc section, would that make sense?

**Comment by jerstlouis** [comment]
@pebau While the general mechanics of Processing is defined in the core OGC API - Processes, and the modular workflow extension would be defined in a _Workflow_ extension to Processes, for the `/processes/wcps` end-point an extension to Coverages would need to define how WCPS can be parameterized and used to deploy process or include as an input to a generic WCPS coverage processor for process execution, and those paths which can be added e.g. to `/processes/{processId}` when using the workflow extensions.

For the `/wcps` end-point, from what I understand there might not be anything to define at all, because you just want to use the existing Web Coverage Processing Service. We could describe it using OpenAPI though, and a server could integrate that OpenAPI definition for the `/wcps` end-point within the overall `/api` of the service.

For the MOAW project I would be interested in us prototyping the `/processes/wcps` end-point mechanics (with parameterized WCPS code) as a facade on top of a rasdaman `/wcps` end-point, thus really demonstrating both approaches.

**Comment by ghobona** [comment]
**2020-09-15 OGC API Cross Cutting Issues session during OGC Member Meeting**

The issue was discussed and there was no objection to the [proposed approach](https://github.com/opengeospatial/ogc_api_coverages/issues/80#issuecomment-692523924).

**Comment by ghobona** [comment]
Given the outcome of the 2020-09-15 OGC API Cross Cutting Issues session, I propose that this issue be closed at the next OGC API - Coverages SWG meeting.

**Comment by pebau** [comment]
So I understand there will be the (approved) `/wcps` together with a process-oriented `/processing/...` - would make sense to me indeed.

**Comment by pebau** [comment]
@ghobona as you close it, can we summarize the result for the generations to come? I understand this is supporting /wcps and /processing/wcps .

**Comment by jerstlouis** [comment]
@ghobona @pebau 

The `/wcps` end-point can be defined, following current WCPS standard.

And here is an xample _OGC API  - Processes_ approach to Coverage processing, using generic expressions:

```json
{
    "process": "https://example.com/ogcapi/processes/coverage-processor",
    "inputs": {
        "data" : [
           { "collection": "https://someserver.com/ogcapi/collections/sentinel2" },
           { "collection": "https://someserver.com/ogcapi/collections/landsat8" }
        ],
        "bandsExpressions" : {
            "value" : {
                "ndvi" : "(ds[0].B08 - ds[0].B04 ) / (ds[0].B04 + ds[0].B08)",
                "lsb4" : "ds[1].B04 / 4000"
            }
        }
    }
}
```

Different coverage processes can exist supporting different languages, e.g. WCPS, Python, etc.

**Comment by pebau** [comment]
@jerstlouis thanks for summarizing! I guess the WPS group will want to update their specs, I can take care of the WCPS part (which requires little change, if at all - will check).

**Comment by jerstlouis** [comment]
@pebau A number of _OGC API - Processes_ issues have recently been resolved  bringing the specifications in line with this, but some updates may still be pending.
That example above however is specific to [Part 3 - Workflows](https://github.com/opengeospatial/ogcapi-processes/tree/master/extensions/workflows), which adds the `collection` types of inputs. and currently makes some things optional like `mode` and `outputs`.
However now that we have a single execution end-point, we will probably want to re-introduce `mode` with new values such as:
- collection (get back a document describing a virtual collection, like you would find at `/collections/{collectionId}`)
- landingPage (get back an OGC API landing page, allowing the process to generate more than a single virtual collection)

So I will add `mode` back in there.
`outputs` would still be made optional by `Workflows`, since the follow-up GET request will be specifying the collection of interest.
